/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyInput {
  'painScore' : bigint,
  'overallScore' : bigint,
  'sleepScore' : bigint,
  'trainingLoadScore' : bigint,
  'stressScore' : bigint,
  'timestamp' : Time,
  'explanations' : string,
}
export interface DisclaimerStatus { 'timestamp' : Time, 'accepted' : boolean }
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'joinedAt' : Time,
  'inviteCode' : string,
  'disclaimerStatus' : [] | [DisclaimerStatus],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateReadinessAndStoreToday' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardData' : ActorMethod<[], [string, [] | [DailyInput], bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];