/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DisclaimerStatus { 'timestamp' : Time, 'accepted' : boolean }
export interface Journaling {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : Principal,
  'isShared' : boolean,
  'squadGroup' : [] | [bigint],
  'timestamp' : Time,
}
export interface Report {
  'id' : bigint,
  'reportedEntry' : [] | [bigint],
  'status' : ReportStatus,
  'reportedUser' : [] | [Principal],
  'timestamp' : Time,
  'details' : [] | [string],
  'reporter' : Principal,
  'reason' : string,
}
export type ReportStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inReview' : null };
export interface SquadGroup {
  'id' : bigint,
  'inviteCreatedAt' : Time,
  'members' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'inviteCode' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'joinedAt' : Time,
  'inviteCode' : string,
  'disclaimerStatus' : [] | [DisclaimerStatus],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDisclaimer' : ActorMethod<[], undefined>,
  'addJournaling' : ActorMethod<
    [string, string, boolean, [] | [bigint]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSquadGroup' : ActorMethod<[string, string], bigint>,
  'deleteJournaling' : ActorMethod<[bigint], undefined>,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuidelines' : ActorMethod<[], string>,
  'getJournaling' : ActorMethod<[bigint], [] | [Journaling]>,
  'getMyJournalEntries' : ActorMethod<[], Array<Journaling>>,
  'getReport' : ActorMethod<[bigint], [] | [Report]>,
  'getSharedSquadEntries' : ActorMethod<[bigint], Array<Journaling>>,
  'getSquadGroup' : ActorMethod<[bigint], [] | [SquadGroup]>,
  'getSquadMembers' : ActorMethod<[bigint], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSquadGroup' : ActorMethod<[string], bigint>,
  'leaveSquadGroup' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'reportAbuse' : ActorMethod<
    [[] | [bigint], [] | [Principal], string, [] | [string]],
    bigint
  >,
  'rotateSquadInviteCode' : ActorMethod<[bigint], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateJournaling' : ActorMethod<
    [bigint, string, string, boolean, [] | [bigint]],
    undefined
  >,
  'updateReportStatus' : ActorMethod<[bigint, ReportStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];